name: Deploy MkDocs Site to GitHub Pages

on:
  push:
    branches:
      - main # O la rama que uses como principal
      # Puedes añadir 'master' si esa es tu rama
  # Permite ejecutar este workflow manualmente desde la pestaña Actions
  workflow_dispatch:

# Permisos para GITHUB_TOKEN para permitir el despliegue a GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite un solo despliegue concurrente, cancela ejecuciones en progreso/pendientes para el mismo grupo
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0 # Para historial completo si usas plugins que lo necesiten

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x # O una versión específica como '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Build site
        run: mkdocs build --verbose

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site' # MkDocs construye el sitio en la carpeta 'site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4